### ISSUE TITLE
Error in Extension

### ISSUE THREAD

**Issue by Gagan557** [mageclass/module-clickandcollect#4]
Please provide when and where (if suitable) you prefer to pick your order message show in checkout page. Next button not work when we enter pickup date

![Screenshot (240)](https://user-images.githubusercontent.com/35591297/59768171-7d4c3300-92c1-11e9-9fd7-e7a6944b75ea.png)

**Comment by SivaMoorthy28** [comment]
HI I fixed this,

Go to view/frontend/web/js/view 

comment line 28 and 48 as below

Line 28 : //$.each(stores, function(index, obj) {

Line 48 : //});

and ,

Replace line 29 as below

$.each(stores.items, function(key, store) {

**Comment by lewisje** [comment]
I was trying to get this module to work, and at first, I thought that the issue was like [this closed JQuery issue](https://bugs.jquery.com/ticket/14649) except that it was about how the `isArrayLike` method throws on numbers rather than on strings, instead of just returning `false`; then I looked at the Issues for this project, and after the change suggested by @SivaMoorthy28, the module worked.

**Comment by sdssrr** [comment]
Which google map api does this module require? Is it Directions api? Geocoding api? Maps Javascript api? Places api? In configuration, I can only set up 1 default map address, how does it deal with multiple store locations and allow "select store by map"?

Any help is greatly appreciated.

**Comment by KowsiganAtsayam** [comment]
I am still facing an error. Which API need to be given? Please tell.
